"""add UniqueConstraint to threads table

Revision ID: 1c46b8d31cfc
Revises: d36eb68c0b8c
Create Date: 2025-12-09 14:17:31.452279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c46b8d31cfc'
down_revision: Union[str, Sequence[str], None] = 'd36eb68c0b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_external_business', 'threads', ['external_thread_id', 'business_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_external_business', 'threads', type_='unique')
    # ### end Alembic commands ###
