"""Add subagent_id to tools and mcp_registry

Revision ID: 2ab2c64a7096
Revises: 1778778abd0d
Create Date: 2025-11-24 09:35:11.772860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ab2c64a7096'
down_revision: Union[str, Sequence[str], None] = '1778778abd0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channels_business_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_name'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_messages_business_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_channel'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.add_column('mcp_registry', sa.Column('subagent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mcp_registry', 'sub_agents', ['subagent_id'], ['id'])
    op.add_column('tools', sa.Column('subagent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tools', 'sub_agents', ['subagent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tools', type_='foreignkey')
    op.drop_column('tools', 'subagent_id')
    op.drop_constraint(None, 'mcp_registry', type_='foreignkey')
    op.drop_column('mcp_registry', 'subagent_id')
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('text_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_channel'), 'messages', ['channel'], unique=False)
    op.create_index(op.f('ix_messages_business_id'), 'messages', ['business_id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('channels_pkey'))
    )
    op.create_index(op.f('ix_channels_name'), 'channels', ['name'], unique=True)
    op.create_index(op.f('ix_channels_business_id'), 'channels', ['business_id'], unique=False)
    # ### end Alembic commands ###
