"""add message_id to thread_messages

Revision ID: 4e2d9095e10b
Revises: 1c46b8d31cfc
Create Date: 2025-12-26 15:24:08.345234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e2d9095e10b'
down_revision: Union[str, Sequence[str], None] = '1c46b8d31cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread_messages', sa.Column('message_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'thread_messages', ['message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thread_messages', type_='unique')
    op.drop_column('thread_messages', 'message_id')
    # ### end Alembic commands ###
