"""remove UpdateEventRecipient table add recipient_business_id to update_events

Revision ID: 73cc6f358b9d
Revises: 3f4915efc9a5
Create Date: 2026-01-01 10:40:19.130459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73cc6f358b9d'
down_revision: Union[str, Sequence[str], None] = '3f4915efc9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_update_event_recipients_recipient_business_id'), table_name='update_event_recipients')
    op.drop_table('update_event_recipients')
    op.add_column('update_events', sa.Column('recipient_business_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('update_events', 'recipient_business_id')
    op.create_table('update_event_recipients',
    sa.Column('update_event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipient_business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['update_event_id'], ['update_events.id'], name=op.f('update_event_recipients_update_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('update_event_id', 'recipient_business_id', name=op.f('update_event_recipients_pkey'))
    )
    op.create_index(op.f('ix_update_event_recipients_recipient_business_id'), 'update_event_recipients', ['recipient_business_id'], unique=False)
    # ### end Alembic commands ###
