"""add message_id in UpdateEvent

Revision ID: 73fa1b603bc5
Revises: daf5d8976d9a
Create Date: 2026-01-01 11:30:15.992371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73fa1b603bc5'
down_revision: Union[str, Sequence[str], None] = 'daf5d8976d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_events', sa.Column('message_id', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('update_events', 'message_id')
    # ### end Alembic commands ###
