"""add business_id to threads table

Revision ID: d36eb68c0b8c
Revises: fb19df7b6cb7
Create Date: 2025-12-08 20:51:07.863325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd36eb68c0b8c'
down_revision: Union[str, Sequence[str], None] = 'fb19df7b6cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('business_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'business_id')
    # ### end Alembic commands ###
