"""rename message_id to msg_id in UpdateEvent

Revision ID: daf5d8976d9a
Revises: 73cc6f358b9d
Create Date: 2026-01-01 11:29:19.515093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf5d8976d9a'
down_revision: Union[str, Sequence[str], None] = '73cc6f358b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_events', sa.Column('msg_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_update_events_message_id'), table_name='update_events')
    op.create_index(op.f('ix_update_events_msg_id'), 'update_events', ['msg_id'], unique=True)
    op.drop_constraint(op.f('update_events_message_id_fkey'), 'update_events', type_='foreignkey')
    op.create_foreign_key(None, 'update_events', 'messages', ['msg_id'], ['id'], ondelete='CASCADE')
    op.drop_column('update_events', 'message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_events', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'update_events', type_='foreignkey')
    op.create_foreign_key(op.f('update_events_message_id_fkey'), 'update_events', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_update_events_msg_id'), table_name='update_events')
    op.create_index(op.f('ix_update_events_message_id'), 'update_events', ['message_id'], unique=True)
    op.drop_column('update_events', 'msg_id')
    # ### end Alembic commands ###
