"""add external_thread_id to table threads

Revision ID: fb19df7b6cb7
Revises: b7b9e83534d3
Create Date: 2025-12-07 21:09:28.712162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb19df7b6cb7'
down_revision: Union[str, Sequence[str], None] = 'b7b9e83534d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('external_thread_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_threads_external_thread_id'), 'threads', ['external_thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threads_external_thread_id'), table_name='threads')
    op.drop_column('threads', 'external_thread_id')
    # ### end Alembic commands ###
