
FROM python:3.11-slim AS base

WORKDIR /app
ENV PYTHONPATH=/app

# Install curl for healthchecks
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Copy requirements first to install dependencies
COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . /app

# Dev target
FROM base AS dev
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9500", "--reload"]


# Prod target
FROM base AS prod
# Copy shared logic and service code
COPY . /app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9500"]
